name: gh-cli

on:
  workflow_dispatch:

jobs:
#  gh-release-view:
#    runs-on: ubuntu-latest
#    steps:
#      - run: gh release view -R vixenlights/vixen --json apiUrl,assets,author,body,createdAt,id,isDraft,isPrerelease,name,publishedAt,tagName,tarballUrl,targetCommitish,uploadUrl,url,zipballUrl

#  gh-release-list:
#    runs-on: ubuntu-latest
#    steps:
#      - run: gh release list -R vixenlights/vixen

#  gh-api-latest:
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#          gh api -H "Accept: application/vnd.github+json" /repos/vixenlights/vixen/releases/latest
  
#  gh-api-releases:
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#          gh api -H "Accept: application/vnd.github+json" /repos/vixenlights/vixen/releases

  get-api-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Where am I and what is here?
        run: |
          pwd
          ls -latr

      - name: Fetch release data
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p data/release
          mkdir -p data/release
          echo foobar > data/release/all.json
          mkdir -p data/release
          gh api -H "Accept: application/vnd.github+json" \
                 /repos/vixenlights/vixen/releases \
                 > data/release/all.json
          gh api -H "Accept: application/vnd.github+json" \
                 /repos/vixenlights/vixen/releases/latest \
                 > data/release/latest.json

      - name: Where am I and what is here? ... again
        run: |
          pwd
          ls -latr
          find data
          ls -latr data/release
