name: gh-cli

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  gh-release-view:
    runs-on: ubuntu-latest
    steps:
      - run: gh release view -R vixenlights/vixen

  gi-release-list:
    runs-on: ubuntu-latest
    steps:
      - run: gh release list -R vixenlights/vixen