name: if-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job1:
    if: github.repository == 'kg9ov/test-actions'
    runs-on: ubuntu-latest
    steps:
      - run: uptime
  
  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - run: uptime
  
  job3:
    needs: [job2]
    runs-on: ubuntu-latest
    steps:
      - run: uptime
